/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.0.0   2018-01-31

The MIT License (MIT)
Copyright (c) 2018 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

/* Includes */
#include "stm32f4xx.h"
#include "proj_common.h"
#include "Uart.h"
#include "Cmds.h"


#define  TICK_INT_PRIORITY            ((uint32_t)0x0F)       /*!< tick interrupt priority */
#define  NVIC_PRIORITYGROUP_4         ((uint32_t)0x00000003) /*!< 4 bits for pre-emption priority
                                                                 0 bits for subpriority */

typedef struct
{
    volatile uint32_t   SysTicks;
} GLOBALS_t;



static GLOBALS_t   Globals;


static void     init_hw(void);
static uint32_t GetSysTick( void );
static uint32_t GetSysDelta( uint32_t OriginalTime );
static void     SystemClock_Config(void);



int main(void)
{
    uint32_t  Ntime;

    Globals.SysTicks = 0;
    Ntime            = 0;

    CMDS_Init();                      // Input Cmd parser
    U1_Init();                        // Uart1: Console Output
    U1Inp_Init();                     // Uart1: Console Input
    init_hw();                        // yeah, does what you think

    CMDS_DisplayVersion();

    while(1)
    {
    	U1_Process();                                      // uart1 (console) output only
    	CMDS_Process();                                    // cmds entered on the command line
    	U1Inp_Process();                                   // uart1 (console) input only

    	if( GetSysDelta(Ntime) >= 500 )                    // 500 is 500ms = 1/2 second
    	{
            GPIO_ToggleBits(GPIOA, GPIO_Pin_15);           // measure on scope
            Ntime = GetSysTick();                          // re-init the count
    	}
    }

    return 0;
}




static void init_gpios(void)
{
    GPIO_InitTypeDef UserLed_gpio;
    GPIO_InitTypeDef Usart1_gpio;

    RCC_AHB1PeriphClockCmd(RCC_AHB1Periph_GPIOA,  ENABLE);
    RCC_APB2PeriphClockCmd(RCC_APB2Periph_USART1, ENABLE);



    GPIO_StructInit(&UserLed_gpio);
      UserLed_gpio.GPIO_Mode  = GPIO_Mode_OUT;
      UserLed_gpio.GPIO_Pin   = GPIO_Pin_15 | GPIO_Pin_0;
      UserLed_gpio.GPIO_PuPd  = GPIO_PuPd_UP;
      UserLed_gpio.GPIO_Speed = GPIO_Speed_50MHz;
    GPIO_Init(GPIOA, &UserLed_gpio);

    GPIO_StructInit(&Usart1_gpio);
      Usart1_gpio.GPIO_Mode  = GPIO_Mode_AF;
      Usart1_gpio.GPIO_Pin   = GPIO_Pin_9 | GPIO_Pin_10;            // Pin 9 (TX), Pin 6 (RX)
      Usart1_gpio.GPIO_PuPd  = GPIO_PuPd_UP;
      Usart1_gpio.GPIO_Speed = GPIO_Speed_50MHz;
      Usart1_gpio.GPIO_OType = GPIO_OType_PP;
    GPIO_Init(GPIOA, &Usart1_gpio);

    GPIO_PinAFConfig(GPIOA, GPIO_PinSource9,  GPIO_AF_USART1);      // The RX and TX pins are now connected to their AF
    GPIO_PinAFConfig(GPIOA, GPIO_PinSource10, GPIO_AF_USART1);      //   so that the USART2 can take over control of the pins
}



static void init_usart1()
{
	USART_InitTypeDef U1;

	USART_StructInit( &U1 );
	  U1.USART_BaudRate            = 9600;
	  U1.USART_WordLength          = USART_WordLength_8b;
	  U1.USART_StopBits            = USART_StopBits_1;
	  U1.USART_Parity              = USART_Parity_No;
	  U1.USART_HardwareFlowControl = USART_HardwareFlowControl_None;
	  U1.USART_Mode                = USART_Mode_Tx | USART_Mode_Rx;
	USART_Init( USART1, &U1 );

	USART_Cmd( USART1, ENABLE );
}





static void init_hw()
{
    RCC_ClocksTypeDef  rclocks;
    uint32_t           prioritygroup = 0;


    FLASH->ACR |= FLASH_ACR_ICEN;      // Flash Instruction Cache Enable
    FLASH->ACR |= FLASH_ACR_DCEN;      // Flash Data Cache Enable
    FLASH->ACR |= FLASH_ACR_PRFTEN;    // Flash Pre-Fetch Buffer Enable

    SystemClock_Config();
    SystemCoreClockUpdate();
    RCC_GetClocksFreq(&rclocks);

    NVIC_SetPriorityGrouping(NVIC_PRIORITYGROUP_4);

    SysTick_Config(rclocks.HCLK_Frequency / 1000);      // 84000000 / 1000 = 84000

    prioritygroup = NVIC_GetPriorityGrouping();

    NVIC_SetPriority(SysTick_IRQn, NVIC_EncodePriority(prioritygroup, TICK_INT_PRIORITY, 0));

    init_gpios();
    init_usart1();
}



static uint32_t GetSysTick( void )
{
    return Globals.SysTicks;
}

static uint32_t GetSysDelta( uint32_t OriginalTime )
{
    uint32_t v = Globals.SysTicks;

    if( v >= OriginalTime )
        return( v - OriginalTime );
    else
        return( ~OriginalTime + 1 + v );
}




void main_systick_handler(void)
{
    GPIO_ToggleBits(GPIOA, GPIO_Pin_0);        // purely for scope measurement
    ++Globals.SysTicks;
}

//====================================================================================================


#define RCC_PLLP_DIV4  ((uint32_t)0x00000004)


static void delay(uint32_t ms)
{
    ms *= 50;
    while(ms--) { __NOP(); }
}


static void SystemClock_Config(void)
{
    SET_BIT(RCC->APB1ENR, RCC_APB1ENR_PWREN);       delay(1);            // __RCC_PWR_CLK_ENABLE()
    MODIFY_REG(PWR->CR, PWR_CR_VOS, PWR_CR_VOS_1);  delay(1);            // __PWR_VOLTAGESCALING_CONFIG(PWR_REGULATOR_VOLTAGE_SCALE2);

    RCC_AdjustHSICalibrationValue(0x0D);                                 // Dialed in to 0x0D using the scope

    RCC_PLLCmd(DISABLE);
    while((RCC->CR & 0x02000000) != RESET) { ; }                         // Already disabled:  will not busy wait here, tested

    //    PLLSource = RCC_PLLSOURCE_HSI;                                 // All these parms from STM32Cube.  401RE project
    //    PLLM      = 16;
    //    PLLN      = 336;
    //    PLLP      = RCC_PLLP_DIV4;
    //    PLLQ      = 7;
    RCC_PLLConfig(RCC_PLLCFGR_PLLSRC_HSI, 16, 336, RCC_PLLP_DIV4, 7);    // This is the big cheese

    RCC_PLLCmd(ENABLE);
    while((RCC->CR & 0x02000000) == RESET) { ; }                         // counting here is like 0x10A, 0x10B.  tested twice.
                                                                         //    so really IS spinning/waiting


    FLASH_SetLatency(FLASH_Latency_2);

    MODIFY_REG(RCC->CFGR, RCC_CFGR_HPRE,   RCC_CFGR_HPRE_DIV1        );
    MODIFY_REG(RCC->CFGR, RCC_CFGR_SW,     RCC_CFGR_SW_PLL           );
    MODIFY_REG(RCC->CFGR, RCC_CFGR_PPRE1,  RCC_CFGR_PPRE1_DIV2       );
    MODIFY_REG(RCC->CFGR, RCC_CFGR_PPRE2, (RCC_CFGR_PPRE1_DIV1 << 3) );
}













